version: "3.9"
services:
  localstack:
    container_name: rds-bug
    image: localstack/localstack-pro:3.0.2
    ports:
      - "443:443"
      - "4566:4566"
      - "4510-4559:4510-4559/tcp"
    environment:
      - SERVICES=s3,sqs,sns,secretsmanager,rds,sts,ec2,cloudformation,ecr,ssm,iam,events
      - DEBUG=1
      - LS_LOG=trace
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_AUTH_TOKEN=PUT_YOUR_TOKEN_HERE
    volumes:
      - ./:/var/lib/localstack/rds_bug
      - ./ready-scripts:/etc/localstack/init/ready.d
      - /var/run/docker.sock:/var/run/docker.sock
